[workspace]
members = [
  "src/adapter-protocol",
  "src/codelldb-launch",
  "src/codelldb-types",
  "src/codelldb",
  "src/lldb-stub",
  "src/lldb",
  "debuggee/rust",
]
resolver = "1"

[profile.release]
debug = true
