[workspace]
members = [
  "adapter/adapter-protocol",
  "adapter/codelldb-launch",
  "adapter/codelldb-types",
  "adapter/codelldb",
  "adapter/lldb-stub",
  "adapter/lldb",
  "debuggee/rust",
]
resolver = "1"

[profile.release]
debug = true
