[package]
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"
name = "codelldb-types"
version = "1.0.0"

[dependencies]
schemars = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
