[package]
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"
name = "adapter-protocol"
version = "1.0.0"

[dependencies]
codelldb-types = {path = "../codelldb-types"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
typify = "0.4.2"
