name: analyze_issue

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        type: number
        required: true

jobs:
  analyze_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Analysis
        uses: vadimcn/codelldbot@master
        with:
          issue_number: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.issue_number || github.event.issue.number }}"
        env:
          SEARCH_REPOSITORY: ${{ vars.SEARCH_REPOSITORY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ vars.ASSISTANT_ID }}
          MODIFY: ${{ vars.MODIFY }}
